name: ww_minimal
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - nextflow=21.04.0
  - bwa=0.7.17
  - samtools=1.12
  - fastp=0.20.1
  - multiqc=1.11
  - bamclipper=1.0.0
  - mosdepth=0.3.2
  - freyja=1.3.1
  - varscan=2.4.4
  - xsv=0.13.0
  - ripgrep=13.0.0
  - pigz=2.6
  - python=3.7
  - pip
  - pip:
    - tqdm
